# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui0.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1261, 723)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_port_com = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_port_com.setGeometry(QtCore.QRect(20, 624, 151, 21))
        self.comboBox_port_com.setObjectName("comboBox_port_com")
        self.Btn_Con = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Con.setGeometry(QtCore.QRect(190, 624, 89, 25))
        self.Btn_Con.setObjectName("Btn_Con")
        self.Btn_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Exit.setGeometry(QtCore.QRect(1130, 620, 89, 25))
        self.Btn_Exit.setObjectName("Btn_Exit")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 20, 1201, 271))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = PlotWidget(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(20, 310, 1201, 271))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 590, 171, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 593, 91, 17))
        self.label.setObjectName("label")
        self.Btn_stop_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_stop_2.setGeometry(QtCore.QRect(300, 625, 89, 25))
        icon = QtGui.QIcon.fromTheme("stop")
        self.Btn_stop_2.setIcon(icon)
        self.Btn_stop_2.setObjectName("Btn_stop_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(390, 592, 113, 25))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(301, 595, 91, 17))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1261, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Btn_Exit.pressed.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trou noir"))
        self.Btn_Con.setText(_translate("MainWindow", "Connect"))
        self.Btn_Exit.setText(_translate("MainWindow", "Exit"))
        self.lineEdit.setText(_translate("MainWindow", "Exp0"))
        self.label.setText(_translate("MainWindow", "Experiment:"))
        self.Btn_stop_2.setText(_translate("MainWindow", "Stop"))
        self.lineEdit_3.setText(_translate("MainWindow", "5"))
        self.label_2.setText(_translate("MainWindow", "Duration[s]:"))
from pyqtgraph import PlotWidget
